.TH man 7 ws_server

.SH NAME
ws_server \- Operation WIRE STORM proxy server

.SH SYNOPSIS
ws_server [\fIOPTIONS\fP]

.SH DESCRIPTION
CTMP proxy server supporting a single source client on port 33333 and multiple
destination clients on port 44444. Forwards valid CTMP messages sent by the
source client to the destination clients.

.SH OPTIONS

.TP
.B -e, --extended
use extended CTMP (includes options and checksum fields)

.TP
.B -n, --num-workers <NUM>
maximum number of client worker threads to use. Default value 32. Accepts a
value between 1 and 64.

.TP
.B -b, --backlog \fP<\fINUM\fP>
backlog length for \fBlisten\fP(2). Default value 32. Accepts a value between 1
and 64. Ensure that \fI/proc/sys/net/core/somaxconn\fP is set to at least 64
(see \fBlisten\fP(2) for details).

.TP
.B -t, --ttl \fP<\fIDURATION\fP>
message time to live in seconds. The cleanup worker frees message data after
this has passed. Default value 5. Accepts a value between 2 and 10.

.TP
.B -h, --help
display help and exit

.SH AUTHOR
Salma Berriche (salma.berriche@gmail.com)

.SH COPYRIGHT
License GPLv2+: GNU GPL version 2 or later: <https://spdx.org/licenses/GPL-2.0.html>
